import { RateLimiter, MINUTE, HOUR } from "@convex-dev/rate-limiter";
import { components } from "../_generated/api";
import type { ActionCtx, MutationCtx } from "../_generated/server";

/**
 * PHASE 5 — Convex-side quota / rate-limiting primitives.
 *
 * Plan/feature *entitlement* lives in Clerk (`has({ plan })` / `has({ feature })`,
 * see ../../lib/entitlements.ts for the server helpers other tracks import).
 * This module covers the complementary concern: bounding *usage* server-side so
 * a single org can't burn unbounded AI calls / writes regardless of plan.
 *
 * Two layers are provided:
 *
 *   1. `rateLimiter` — the shared @convex-dev/rate-limiter instance with named
 *      limits, keyed per-org. Use `enforceRateLimit(ctx, name, orgId)` from a
 *      mutation/action to consume a token and throw when exhausted.
 *
 *   2. `usageMeters` helpers (in ../billing.ts) — durable per-period counters
 *      for plan quotas (e.g. "5,000 AI replies / month on Pro"). Those are
 *      simple denormalized counters; this file owns the burst/abuse limits.
 *
 * NOTE (merge stage): `components.rateLimiter` types are only generated by a
 * full `convex deploy` (the merge stage performs the single authoritative
 * deploy). `npx convex codegen` alone may not yet know about the component, so
 * the `components.rateLimiter` reference below can show a transient type error
 * until deploy. That is expected per the Wave A build rules — do not block on it.
 */

/**
 * Named rate limits, keyed per-org via the `key` option at call sites.
 *
 * Tune these as consuming tracks land. Periods are in milliseconds (the
 * component exports MINUTE / HOUR helpers).
 */
export const rateLimiter = new RateLimiter(components.rateLimiter, {
  // Burst limit for AI agent replies — protects the OpenAI spend per org.
  // ~60/min sustained, allowing short bursts of 20.
  aiMessage: { kind: "token bucket", rate: 60, period: MINUTE, capacity: 20 },
  // Knowledge-base document ingestion (PDF parse / embedding) per org.
  kbIngest: { kind: "token bucket", rate: 30, period: MINUTE, capacity: 10 },
  // Widget visitor session creation per org (anti-abuse on the public surface).
  widgetSession: { kind: "fixed window", rate: 600, period: MINUTE },
  // Outbound email / notification sends per org.
  notification: { kind: "token bucket", rate: 100, period: HOUR, capacity: 20 },
});

/** Names of the configured rate limits — exported for typed call sites. */
export type RateLimitName =
  | "aiMessage"
  | "kbIngest"
  | "widgetSession"
  | "notification";

export interface EnforceRateLimitResult {
  ok: boolean;
  /** Epoch ms when the caller may retry, when `ok` is false. */
  retryAfter?: number;
}

/**
 * Consume `count` units of a named rate limit, scoped to `orgId`.
 *
 * Pass `throws: true` to raise a `ConvexError` (surfaced to the client) instead
 * of returning `{ ok: false }`. Other tracks import this from their
 * mutations/actions, e.g.:
 *
 *   await enforceRateLimit(ctx, "aiMessage", ctx.orgId, { throws: true });
 *
 * Consuming a token is a *write* to the rate-limiter component, so this must be
 * called from a mutation or action — not a query (queries are read-only).
 */
export async function enforceRateLimit(
  ctx: MutationCtx | ActionCtx,
  name: RateLimitName,
  orgId: string,
  opts?: { count?: number; throws?: boolean },
): Promise<EnforceRateLimitResult> {
  const { ok, retryAfter } = await rateLimiter.limit(ctx, name, {
    key: orgId,
    count: opts?.count ?? 1,
    throws: opts?.throws ?? false,
  });
  return { ok, retryAfter: retryAfter ?? undefined };
}
